// src/styles/theme.js
// ── Design tokens & component styles ──────────────────────────────────────

export const C = {
  bg:          "#070d1a",
  card:        "#0d1b2e",
  cardBorder:  "#1a3050",
  accent:      "#1e6fd9",
  accentLight: "#3b82f6",
  gold:        "#c9a227",
  text:        "#e2eaf4",
  muted:       "#7a9cc0",
  success:     "#10b981",
};

export const styles = {
  root: { minHeight: "100vh", background: C.bg, color: C.text, fontFamily: "'Georgia', serif", display: "flex", flexDirection: "column" },
  // Ads
  adBanner:         { background: "#060c18", borderBottom: "1px solid #111f35", padding: "8px 16px", display: "flex", flexDirection: "column", alignItems: "center" },
  adLabel:          { fontSize: 10, color: "#2a4a6a", letterSpacing: 2, textTransform: "uppercase", marginBottom: 4 },
  adSlot:           { width: "100%", maxWidth: 728, height: 90, background: "#0c1a2e", border: "1px dashed #1a3050", borderRadius: 4, display: "flex", alignItems: "center", justifyContent: "center" },
  adPlaceholderText:{ color: "#2a4a6a", fontSize: 13, textAlign: "center" },
  sideAd:           { width: 160, flexShrink: 0, marginLeft: 20, display: "flex", flexDirection: "column", alignItems: "center" },
  sideAdSlot:       { width: 160, height: 600, background: "#0c1a2e", border: "1px dashed #1a3050", borderRadius: 4, display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center", padding: 8, boxSizing: "border-box" },
  // Header
  header:       { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 32px", background: "#0a1525", borderBottom: "1px solid #1a3050", position: "sticky", top: 0, zIndex: 100 },
  logoWrap:     { display: "flex", alignItems: "center", gap: 10 },
  logoIcon:     { fontSize: 26, color: C.gold },
  logoText:     { fontSize: 22, fontWeight: "bold", color: C.text, letterSpacing: 1 },
  nav:          { display: "flex", gap: 8 },
  navBtn:       { padding: "8px 18px", borderRadius: 8, border: "1px solid #1a3050", background: "transparent", color: C.muted, cursor: "pointer", fontSize: 14, fontFamily: "Georgia,serif", transition: "all .2s" },
  navBtnActive: { background: C.accent, color: "#fff", borderColor: C.accent },
  // Token bar
  tokenBar:      { background: "#0b1929", borderBottom: "1px solid #1a3050", padding: "10px 32px" },
  tokenBarInner: { maxWidth: 900, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-around", flexWrap: "wrap", gap: 12 },
  tokenItem:     { display: "flex", flexDirection: "column", alignItems: "center", gap: 2 },
  tokenLabel:    { fontSize: 10, color: C.muted, letterSpacing: 2, textTransform: "uppercase" },
  tokenNumber:   { fontSize: 22, fontWeight: "bold", color: "#7eb8f7", letterSpacing: 2, fontFamily: "monospace" },
  tokenDivider:  { width: 1, height: 40, background: "#1a3050" },
  // Layout
  main: { display: "flex", padding: "24px 32px", gap: 0, flex: 1, maxWidth: 1200, margin: "0 auto", width: "100%", boxSizing: "border-box" },
  page: { flex: 1 },
  // Hero
  heroCard:      { display: "flex", gap: 32, background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 16, padding: 32, marginBottom: 28, flexWrap: "wrap" },
  heroLeft:      { display: "flex", flexDirection: "column", alignItems: "center", gap: 16, minWidth: 200 },
  heroRight:     { flex: 1, minWidth: 260 },
  doctorPhoto:   { width: 160, height: 160, borderRadius: "50%", objectFit: "cover", border: `3px solid ${C.gold}`, boxShadow: "0 0 32px rgba(201,162,39,.3)" },
  statRow:       { display: "flex", gap: 12 },
  statBox:       { display: "flex", flexDirection: "column", alignItems: "center", background: "#0a1525", borderRadius: 10, padding: "8px 14px", border: "1px solid #1a3050" },
  statValue:     { fontSize: 18, fontWeight: "bold", color: "#7eb8f7" },
  statLabel:     { fontSize: 10, color: C.muted, textTransform: "uppercase", letterSpacing: 1 },
  badge:         { display: "inline-block", background: "rgba(16,185,129,.15)", color: C.success, border: "1px solid rgba(16,185,129,.3)", borderRadius: 20, padding: "4px 14px", fontSize: 12, marginBottom: 10 },
  doctorName:    { fontSize: 32, fontWeight: "bold", margin: "0 0 6px", color: "#f0f8ff" },
  doctorTitle:   { color: C.gold, fontSize: 16, margin: "0 0 8px" },
  doctorHospital:{ color: C.muted, fontSize: 14, margin: "0 0 4px" },
  doctorTimings: { color: "#34d399", fontSize: 13, margin: "0 0 12px" },
  doctorAbout:   { color: "#9bb8d8", fontSize: 14, lineHeight: 1.7, margin: "0 0 16px" },
  contactRow:    { display: "flex", gap: 10, flexWrap: "wrap" },
  contactBtn:    { padding: "8px 16px", borderRadius: 8, background: "#0a1525", border: "1px solid #1a3050", color: "#7eb8f7", textDecoration: "none", fontSize: 13 },
  bookBtn:       { padding: "12px 28px", borderRadius: 10, background: "linear-gradient(135deg,#1e40af,#3b82f6)", color: "#fff", border: "none", cursor: "pointer", fontSize: 16, fontFamily: "Georgia,serif", fontWeight: "bold", letterSpacing: .5, boxShadow: "0 4px 20px rgba(59,130,246,.35)" },
  // Sections
  section:      { background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 16, padding: 28, marginBottom: 24 },
  sectionTitle: { fontSize: 20, color: C.gold, marginBottom: 20, borderBottom: "1px solid #1a3050", paddingBottom: 10 },
  degreeGrid:   { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))", gap: 16 },
  degreeCard:   { background: "#0a1525", border: "1px solid #1a3050", borderRadius: 12, padding: 18, borderLeft: `3px solid #1e6fd9` },
  degreeYear:   { fontSize: 12, color: C.muted, marginBottom: 6 },
  degreeTitle:  { fontWeight: "bold", color: "#e0f0ff", marginBottom: 4 },
  degreeInst:   { fontSize: 13, color: C.muted },
  certList:     { display: "flex", flexDirection: "column", gap: 12 },
  certItem:     { display: "flex", alignItems: "center", gap: 12, background: "#0a1525", border: "1px solid #1a3050", borderRadius: 10, padding: "12px 18px" },
  certIcon:     { color: C.gold, fontSize: 14 },
  // Book
  bookCard:   { background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 16, padding: 36, maxWidth: 500 },
  bookTitle:  { fontSize: 26, color: "#e0f0ff", marginBottom: 6 },
  bookSub:    { color: C.muted, fontSize: 14, marginBottom: 24 },
  formLabel:  { display: "block", color: C.muted, fontSize: 13, marginBottom: 6, letterSpacing: .5 },
  input:      { width: "100%", padding: "12px 14px", borderRadius: 10, border: "1px solid #1a3050", background: "#0a1525", color: C.text, fontSize: 15, fontFamily: "Georgia,serif", marginBottom: 18, boxSizing: "border-box" },
  radioGroup: { display: "flex", gap: 16, flexWrap: "wrap", marginBottom: 10 },
  radioLabel: { color: C.muted, fontSize: 14, cursor: "pointer" },
  tokenPreview:{ background: "#0a1a30", border: "1px solid #1e6fd9", borderRadius: 10, padding: "12px 18px", color: "#7eb8f7", fontSize: 15, marginTop: 10 },
  warningBox: { background: "#2d1f00", border: "1px solid #f59e0b", borderRadius: 10, padding: "12px 16px", color: "#fcd34d", fontSize: 14, marginBottom: 20 },
  // Success
  successCard:   { background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 16, padding: 40, maxWidth: 480, textAlign: "center" },
  successIcon:   { fontSize: 52, marginBottom: 12 },
  successTitle:  { fontSize: 26, color: C.success, marginBottom: 24 },
  bigToken:      { display: "flex", flexDirection: "column", alignItems: "center", background: "#0a1a30", border: "1px solid #1e6fd9", borderRadius: 16, padding: "20px 40px", marginBottom: 24 },
  bigTokenLabel: { fontSize: 12, color: C.muted, letterSpacing: 2, textTransform: "uppercase" },
  bigTokenNum:   { fontSize: 52, fontWeight: "bold", color: "#7eb8f7", fontFamily: "monospace", letterSpacing: 4 },
  successInfo:   { color: C.muted, fontSize: 14, lineHeight: 1.9, marginBottom: 16 },
  notifBox:      { background: "#0a1a30", borderRadius: 10, padding: "12px 16px", marginBottom: 20, fontSize: 14, color: "#7eb8f7" },
  successNote:   { color: C.muted, fontSize: 13, marginBottom: 24 },
  // Admin
  adminLoginCard:    { background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 16, padding: 40, maxWidth: 400, textAlign: "center" },
  lockIcon:          { fontSize: 48, marginBottom: 16 },
  errorText:         { color: "#f87171", fontSize: 14, marginTop: -10, marginBottom: 10 },
  adminCard:         { background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 16, padding: 32, width: "100%" },
  progressSection:   { marginBottom: 28 },
  progressHeader:    { display: "flex", justifyContent: "space-between", color: C.muted, fontSize: 13, marginBottom: 8 },
  progressBar:       { height: 12, background: "#0a1525", borderRadius: 6, overflow: "hidden", border: "1px solid #1a3050" },
  progressFill:      { height: "100%", background: "linear-gradient(90deg,#1e40af,#10b981)", borderRadius: 6, transition: "width .4s" },
  adminTokenDisplay: { display: "flex", gap: 20, marginBottom: 24, flexWrap: "wrap" },
  adminTokenBox:     { flex: 1, minWidth: 150, background: "#0a1525", border: "1px solid #1a3050", borderRadius: 14, padding: "20px 24px", textAlign: "center" },
  adminTokenLabel:   { display: "block", fontSize: 11, color: C.muted, letterSpacing: 2, textTransform: "uppercase", marginBottom: 8 },
  adminTokenNum:     { fontSize: 44, fontWeight: "bold", color: "#7eb8f7", fontFamily: "monospace", letterSpacing: 4 },
  adminBtnRow:       { display: "flex", gap: 16, flexWrap: "wrap" },
  apptTable:         { overflowX: "auto", borderRadius: 10, border: "1px solid #1a3050" },
  apptRow:           { display: "grid", gridTemplateColumns: "80px 1fr 1.5fr 1.2fr 1fr", borderBottom: "1px solid #0f1f35", minWidth: 600 },
  apptRowActive:     { background: "rgba(16,185,129,.08)", borderLeft: "3px solid #10b981" },
  apptHeader:        { padding: "10px 14px", fontSize: 11, color: C.muted, letterSpacing: 1, textTransform: "uppercase", background: "#081526" },
  apptCell:          { padding: "10px 14px", fontSize: 13, color: C.text },
  footer:            { textAlign: "center", padding: "20px 16px", color: "#2a4a6a", fontSize: 13, borderTop: "1px solid #111f35" },
};
